import 'package:dartantic_ai/dartantic_ai.dart';
import 'package:magic_recipe_server/src/recipes/recipes.dart';

class MockRecipeAIService extends RecipeAIService {
  MockRecipeAIService([this.output = 'Mock Recipe']);

  final String output;
  final List<String> prompts = [];

  @override
  Future<ChatResult<String>> generateContent(
    String prompt, {
    List<Part> attachments = const [],
    List<ChatMessage> history = const [],
  }) {
    if (history.isNotEmpty) {
      // The prompt generated by recipe service is stored inside the history
      // objects when interacting with the dartantic_ai agent.
      // E.g. UserMessage(parts: [TextPart(text: Generate a recipe using...)])
      prompts.add(history.toString());
    } else {
      prompts.add(prompt);
    }
    return Future.value(ChatResult<String>(output: output));
  }
}
